### ISSUE TITLE
Option to disable highlight when switching tabs

### ISSUE THREAD

**Issue by brady444** [darlal/obsidian-switcher-plus#209]
When switching to an already open tab, there is a short highlight effect. I'd like an option to remove this.

Doing some testing, I found that if you remove the call to `revealLeaf` [here](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/Handlers/handler.ts#L395), then the highlight doesn't show. But I'm not sure if this causes any side effects if the tab is in the sidebar or something.

Thank you.

**Comment by brady444** [comment]
Made a CSS snippet:
```css
.workspace-tab-header.is-flashing {
	transition: unset;
	mix-blend-mode: unset;
	background-color: var(--tab-background-active) !important;
}
```

It's better than modifying the code directly, but may still have some visual side effects. Works well enough for me though.
